### ISSUE TITLE
Left menu

### ISSUE THREAD

**Issue by scharffc** [appdockProject/appDockApp#4]
Please be sure the left menu is updated.

@jangerhard @vjrene @agreenberg18 @FrankJWH @noncreativetype 

The button COMMENTAIRES is changed into ENQUETE. We are removing the accents on the titles of the buttons. The buttons on the left should be re-organized in this order :

EDUCATION

APPLICATIONS

DEVELOPPEURS

ENQUETE (was COMMENTAIRES)

FACEBOOK

As the goal of the app os education, education should be first.

**Comment by jangerhard** [comment]
Titles changed in 573c726. 

Still working on changing the order everywhere.
