### ISSUE TITLE
Titles of the screens

### ISSUE THREAD

**Issue by scharffc** [appdockProject/appDockApp#5]
@jangerhard @vjrene @agreenberg18 @FrankJWH @noncreativetype

Concerning the titles at the top of each screen, we will change them as this: 

Screen Education : Vidéos sur l’utilisation des téléphones (PLEASE NOTE i CHANGED THIS AGAIN)

Screen Applications : Applications mobiles du Sénégal

Screen Developpeurs : Développeurs du Sénégal

Screen ENQUETE : Enquête sur AppDock

Screen Facebook : Partage d’expérience en photo

**Comment by jangerhard** [comment]
Fixed in commit c469a9d.
