### ISSUE TITLE
9 screens for the applications

### ISSUE THREAD

**Issue by scharffc** [appdockProject/appDockApp#8]
The SMS textbox should be the default one.

The button should use the whole space. 

Can you be sure the buttons are of the same size in height as the buttons on the left?

**Comment by vjrene** [comment]
<img width="712" alt="screen shot 2016-11-01 at 1 44 06 pm" src="https://cloud.githubusercontent.com/assets/19736616/19900053/951c54c0-a038-11e6-9688-cd0f214c0013.png">
